# Pandas 
```
pip install pandas 
pip install --upgrade pandas
```
- Pandas Series
- Pandas DataFrame --> use various ways to initialize it(dtype,columns,index)
- Add a column: using name and list
- shape
- head
- tail
- convert to numpy array --> values
- columns
- to_csv (index = false)
- read_csv
-  drop(columns=[])
-  describe()
-  info()
-  iloc
-  loc
-  Access Particular Columns
-  indexing and slicing --> multirow and col
-  columns.get_loc
-  Fancy indexing
-  Filtering
-  unique
-  sort_values(by,ascending)
-  getdummies 
- groupby --> column name, various functions on grp, iterate
- pivot --> summarize and aggregate data,Grouper
- concat--> give as list, ignore_index,join
- merge--> on,how
- dropna
- fillna
- interpolate
- pip install matplotlib

In [4]:
import pandas as pd
import numpy as np

In [5]:
print(pd.__version__)

2.2.3


In [26]:
l1 = np.array([10,20,30,40,50])
d1 = {'A':20,'B':100,'C':10}

In [27]:
# pds = pd.Series(l1,index = ['A','B','C','D','E'],dtype='f8')
pds = pd.Series(d1)

In [28]:
pds

A     20
B    100
C     10
dtype: int64

In [24]:
type(pds)

pandas.core.series.Series

In [25]:
pds['A']

10.0

In [36]:
marks = {
    'Phy': [85,95,90,65,78],
    'Chem': [95,65,80,75,99],
    'Maths':[98,79,94,83,80]
}

In [37]:
marks

{'Phy': [85, 95, 90, 65, 78],
 'Chem': [95, 65, 80, 75, 99],
 'Maths': [98, 79, 94, 83, 80]}

In [48]:
df = pd.DataFrame(marks,index=['A','B','C','D','E'],columns=['Phy','Maths','Chem'])

In [49]:
df

Phy  Maths  Chem
A   85     98    95
B   95     79    65
C   90     94    80
D   65     83    75
E   78     80    99

In [50]:
na = np.random.randint(1,101,size = (10,3))

In [57]:
df2 = pd.DF(na,columns=['Physics','Chemistry','Mathematics'])

In [59]:
df2['SST'] = np.random.randint(1,101,size=(10,))

In [60]:
df2

Physics  Chemistry  Mathematics  SST
0       94          9           98    8
1       56         34           98   93
2       70         58           42   57
3       23         84           21   76
4       99         20           57   40
5       65         52           17   79
6       56         84           65   74
7       15         50           24   68
8       41         15           76   25
9       38         42           14   39

In [62]:
df2.shape

(10, 4)

In [65]:
df2.head(3)

Physics  Chemistry  Mathematics  SST
0       94          9           98    8
1       56         34           98   93
2       70         58           42   57

In [66]:
df2.tail(3)

Physics  Chemistry  Mathematics  SST
7       15         50           24   68
8       41         15           76   25
9       38         42           14   39

In [67]:
df.values

array([[85, 98, 95],
       [95, 79, 65],
       [90, 94, 80],
       [65, 83, 75],
       [78, 80, 99]], dtype=int64)

In [68]:
df.columns

Index(['Phy', 'Maths', 'Chem'], dtype='object')

In [69]:
df2.columns

Index(['Physics', 'Chemistry', 'Mathematics', 'SST'], dtype='object')

In [70]:
df

Phy  Maths  Chem
A   85     98    95
B   95     79    65
C   90     94    80
D   65     83    75
E   78     80    99

In [83]:
df.to_csv("Marks.csv",sep='|')

In [86]:
ndf = pd.read_csv("Marks.csv",sep='|',index_col='Unnamed: 0')

In [87]:
ndf

Phy  Maths  Chem
A   85     98    95
B   95     79    65
C   90     94    80
D   65     83    75
E   78     80    99

In [88]:
df.to_csv("Marks.csv",sep='|',index=False)

In [89]:
ndf = pd.read_csv("Marks.csv",sep='|')
ndf

Phy  Maths  Chem
0   85     98    95
1   95     79    65
2   90     94    80
3   65     83    75
4   78     80    99

In [90]:
ndf.index = ['A','B','C','D','E']

In [91]:
ndf

Phy  Maths  Chem
A   85     98    95
B   95     79    65
C   90     94    80
D   65     83    75
E   78     80    99

In [92]:
df

Phy  Maths  Chem
A   85     98    95
B   95     79    65
C   90     94    80
D   65     83    75
E   78     80    99

In [95]:
df2.astype('f8')

Physics  Chemistry  Mathematics   SST
0     94.0        9.0         98.0   8.0
1     56.0       34.0         98.0  93.0
2     70.0       58.0         42.0  57.0
3     23.0       84.0         21.0  76.0
4     99.0       20.0         57.0  40.0
5     65.0       52.0         17.0  79.0
6     56.0       84.0         65.0  74.0
7     15.0       50.0         24.0  68.0
8     41.0       15.0         76.0  25.0
9     38.0       42.0         14.0  39.0

In [98]:
df.drop(columns=['Chem'],inplace=True)

In [100]:
df.drop(index=['A','C'])

Phy  Maths
B   95     79
D   65     83
E   78     80

In [102]:
df2

Physics  Chemistry  Mathematics  SST
0       94          9           98    8
1       56         34           98   93
2       70         58           42   57
3       23         84           21   76
4       99         20           57   40
5       65         52           17   79
6       56         84           65   74
7       15         50           24   68
8       41         15           76   25
9       38         42           14   39

In [103]:
df2.describe()

Physics  Chemistry  Mathematics        SST
count  10.000000  10.000000    10.000000  10.000000
mean   55.700000  44.800000    51.200000  55.900000
std    27.664859  26.321938    32.505726  27.032696
min    15.000000   9.000000    14.000000   8.000000
25%    38.750000  23.500000    21.750000  39.250000
50%    56.000000  46.000000    49.500000  62.500000
75%    68.750000  56.500000    73.250000  75.500000
max    99.000000  84.000000    98.000000  93.000000

In [104]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Physics      10 non-null     int32
 1   Chemistry    10 non-null     int32
 2   Mathematics  10 non-null     int32
 3   SST          10 non-null     int32
dtypes: int32(4)
memory usage: 292.0 bytes


In [111]:
df[['Maths','Phy']]

Maths  Phy
A     98   85
B     79   95
C     94   90
D     83   65
E     80   78

In [112]:
df.loc['A','Maths']

98

In [120]:
df.loc[['A','C','D'],['Phy','Maths']]

Phy  Maths
A   85     98
C   90     94
D   65     83

In [115]:
df2.loc[0]

Physics        94
Chemistry       9
Mathematics    98
SST             8
Name: 0, dtype: int32

In [128]:
df.iloc[0,1] = 100

In [129]:
df

Phy  Maths
A   85    100
B   95     79
C   90     94
D   65     83
E   78     80

In [131]:
df2.iloc[2:6,1:3]

Chemistry  Mathematics
2         58           42
3         84           21
4         20           57
5         52           17

In [127]:
df2.loc[2:5,'Chemistry':'Mathematics']

Chemistry  Mathematics
2         58           42
3         84           21
4         20           57
5         52           17

In [134]:
df[df['Phy'] > 80]

Phy  Maths
A   85    100
B   95     79
C   90     94

In [135]:
wdf = pd.read_csv('weather_data_cities.csv')

In [144]:
mumbaidf = wdf[wdf['city'] == 'mumbai']

In [146]:
mumbaidf[mumbaidf['temperature'] >= 90]['day']

4    1/1/2017
7    1/4/2017
Name: day, dtype: object

In [166]:
wdf[(wdf['city'] == 'mumbai') & (wdf['temperature'] >= 90)]

day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
7  1/4/2017  mumbai           92          5   Rain

In [168]:
wdf.columns.get_loc('city')

1

In [109]:
df[df['Phy'] >= 73]

Phy  Chem  Maths
A   74    41     65
D   98    56     56

In [119]:
df.columns

Index(['Phy', 'Chem', 'Maths'], dtype='object')

In [112]:
df.columns.get_loc('Maths')

2

In [169]:
df

Phy  Maths
A   85    100
B   95     79
C   90     94
D   65     83
E   78     80

In [170]:
df['Phy'].unique()

array([85, 95, 90, 65, 78], dtype=int64)

In [175]:
pd.unique(df['Phy'])

array([85, 95, 90, 65, 78], dtype=int64)

In [171]:
a = np.array([1,3,1,2,4,1,3,2,4,1,2,3,1,4])

In [173]:
np.unique(a,return_counts=True)

(array([1, 2, 3, 4]), array([5, 3, 3, 3], dtype=int64))

In [179]:
df2['Chemistry'].apply(lambda x: x**2)

0      81
1    1156
2    3364
3    7056
4     400
5    2704
6    7056
7    2500
8     225
9    1764
Name: Chemistry, dtype: int64

In [181]:
df.sort_values(by = 'Phy',axis = 0,ascending=False)

Phy  Maths
B   95     79
C   90     94
A   85    100
E   78     80
D   65     83

In [182]:
df.sort_values(by = 'A',axis = 1,ascending=False)

Maths  Phy
A    100   85
B     79   95
C     94   90
D     83   65
E     80   78

In [183]:
pds = pd.Series(['A','B','C','B','A','B'])

In [189]:
pds

0    A
1    B
2    C
3    B
4    A
5    B
dtype: object

In [191]:
pdd = pd.get_dummies(pds,dtype='i1',prefix='y')

In [192]:
pdd

y_A  y_B  y_C
0    1    0    0
1    0    1    0
2    0    0    1
3    0    1    0
4    1    0    0
5    0    1    0

In [193]:
data = pd.read_csv("weather_data_cities.csv")

In [194]:
data

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [195]:
data.iloc[data['temperature'].argmax()]

day            1/4/2017
city             mumbai
temperature          92
windspeed             5
event              Rain
Name: 7, dtype: object

In [152]:
data[data['temperature'] == data['temperature'].max()]

day    city  temperature  windspeed event
7  1/4/2017  mumbai           92          5  Rain

In [199]:
gdf = data.groupby(by = 'city')

In [200]:
for city,group in gdf:
    print(city)
    print(group)
    print()

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny

paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy



In [201]:
gdf['temperature'].max()

city
mumbai      92
new york    36
paris       54
Name: temperature, dtype: int64

In [202]:
gdf = data.groupby(by = 'event')
gdf['windspeed'].mean()

event
Cloudy    10.333333
Fog       13.500000
Rain       5.500000
Snow      12.000000
Sunny      9.750000
Name: windspeed, dtype: float64

In [165]:
data

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [206]:
data.pivot(columns='city',index='day')

temperature                windspeed                 event           \
city          mumbai new york paris    mumbai new york paris mumbai new york   
day                                                                            
1/1/2017          90       32    45         5        6    20  Sunny     Rain   
1/2/2017          85       36    50        12        7    13    Fog    Sunny   
1/3/2017          87       28    54        15       12     8    Fog     Snow   
1/4/2017          92       33    42         5        7    10   Rain    Sunny   

                  
city       paris  
day               
1/1/2017   Sunny  
1/2/2017  Cloudy  
1/3/2017  Cloudy  
1/4/2017  Cloudy

In [207]:
d1 = {
    'A' : [10,20,30,40],
    'B' : [3,4,5,6]
}
d2 = {
    'A' : [30,40,50,60],
    'C' : [3,4,5,6]
}

In [208]:
df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)

In [209]:
df1

A  B
0  10  3
1  20  4
2  30  5
3  40  6

In [210]:
df2

A  C
0  30  3
1  40  4
2  50  5
3  60  6

In [214]:
df3 = pd.concat([df1,df2],axis=1)
df3

A  B   A  C
0  10  3  30  3
1  20  4  40  4
2  30  5  50  5
3  40  6  60  6

In [219]:
mdf3 = pd.merge(df1,df2,how='right')
mdf3

A    B  C
0  30  5.0  3
1  40  6.0  4
2  50  NaN  5
3  60  NaN  6

In [220]:
mdf3.dropna()

A    B  C
0  30  5.0  3
1  40  6.0  4

In [221]:
mdf3.fillna(mdf3.mean())

A    B  C
0  30  5.0  3
1  40  6.0  4
2  50  5.5  5
3  60  5.5  6

In [222]:
mdf3.mean()

A    45.0
B     5.5
C     4.5
dtype: float64

In [223]:
mdf3.interpolate('linear',limit_direction='both')

A    B  C
0  30  5.0  3
1  40  6.0  4
2  50  6.0  5
3  60  6.0  6

In [196]:
arr = np.array([1,2,3,2,3])
arr.argmax()

2