# Numpy
```
pip install numpy
```

- Mathematical Calculations
- Numpy Array Creation
- Shape
- indexing
- data types: b,i,u,f,c,m,M,O,S,u,V (https://numpy.org/doc/1.25/reference/arrays.dtypes.html#arrays-dtypes)
- more creation methods: arange, linspace, ones, zeros, eye, diag
- random numbers: Numpy Random Module
    - rand: Random values in given shape
    - randn: Return samples from the Standard normal distribution
    - randint: Return random integer from low(inclusive) to high(exclusive)
    - random: Return random floats in [0.0,1.0)
    - choice: Generates a random sample from given 1D array
    - Shuffle: Shuffle the contents of the sequence. Discuss np.random.seed()
- reshape: -1 for unknown
- slicing and assignment
- copy and view: share_memory
- operators(Element wise operations)
- and: &, or: |, not: ~ (Bitwise works same as logical in case of boolean Values)
- shape mismatch
- fancy indexing also know as filter
- search: where uses fancy indexing
- Basic reductions: sum, min, max, any, all,argmax, argmin
- Some More Numpy Functions - Statistics: mean, median, average, variance, standard deviation
- iteration: nditer, ndenumerate
- Join: concatenate, stack, hstack, vstack. Note: make a tuple of arays you want to join
- split: array_split, hsplit
- sort: np.sort
- Broadcasting
- Input from Text File
- Questions

In [1]:
!pip install numpy

In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [26]:
l1 = [1,2,3,4]
l2 = [[1,2],[3,4],[5,6]]
l3 = [[[10,20],[30,40]],[[1,2],[3,4]],[[1,2],[3,4]]]

In [48]:
n1 = np.array(l1,dtype='f8')
n2 = np.array(l2,dtype='i1')#1 2 4 8
n3 = np.array(l3)

In [49]:
n2.dtype

dtype('int8')

In [29]:
n2.shape

(3, 2)

In [30]:
n3.shape

(3, 2, 2)

In [32]:
print(l1[2],n1[2])

3 3


In [34]:
# print(l2[1][1], n2[1][1])
print(l2[1][1], n2[1,1])

4 4


In [37]:
print(l3[0][1][0],n3[0,1,0])

30 30


In [38]:
l2[1]

[3, 4]

In [41]:
n2[1]

array([3, 4])

In [42]:
n2[1,2,1]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

more creation methods: arange, linspace, ones, zeros, eye, diag

In [51]:
narr = np.arange(1,11)

In [52]:
narr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [58]:
np.ones(shape = (5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [59]:
np.zeros(shape=(5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [70]:
np.eye(2,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [71]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [73]:
narr = np.arange(1,101)

In [75]:
narr = narr.reshape((10,10))

In [76]:
narr.shape

(10, 10)

In [77]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

random numbers: Numpy Random Module
- rand: Random values in given shape
- randn: Return samples from the Standard normal distribution
- randint: Return random integer from low(inclusive) to high(exclusive)
- random: Return random floats in [0.0,1.0)
- choice: Generates a random sample from given 1D array
- Shuffle: Shuffle the contents of the sequence. Discuss np.random.seed()

In [78]:
np.random.rand(3,2,2)

array([[[0.72016251, 0.2797445 ],
        [0.58225106, 0.33101301]],

       [[0.87272389, 0.96126775],
        [0.30356076, 0.02311402]],

       [[0.6448465 , 0.04280286],
        [0.08959913, 0.68817352]]])

In [79]:
np.random.randn(3,2,2)

array([[[ 1.7905566 , -0.30765327],
        [ 0.2377005 ,  0.5311676 ]],

       [[-1.00601621,  1.17516584],
        [-0.18181411,  0.01083942]],

       [[ 1.25232093,  0.46223587],
        [-0.15167277,  0.50397596]]])

In [80]:
np.random.randint(1,101,size=(5,2))

array([[61, 37],
       [46, 67],
       [82, 97],
       [23, 94],
       [35, 11]])

In [81]:
np.random.random(size=(5,2))

array([[0.34975688, 0.82344578],
       [0.57413113, 0.9799406 ],
       [0.43098886, 0.8674576 ],
       [0.56836466, 0.88558562],
       [0.72232498, 0.80616593]])

In [97]:
np.random.choice(np.array([1,2,3,4,5,6,7,8,9]),size=(5,),replace = True,p = [0,0,0,0,0.3,0.3,0.1,0.3,0])

array([6, 5, 8, 6, 6])

In [101]:
narr = np.arange(1,101).reshape((10,10))
np.random.shuffle(narr)

In [102]:
narr

array([[ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50]])

In [115]:
narr = np.arange(1,101)

In [106]:
narr = narr.reshape((5,2,-1))

In [107]:
narr

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60]],

       [[ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]]])

In [110]:
narr.reshape((-1,))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [113]:
narr[1,1,4] = 350

In [114]:
narr

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34, 350,  36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60]],

       [[ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]]])

In [119]:
narr = narr.reshape((5,2,-1))

In [122]:
narr[1,1,4] = 350

In [137]:
narr[1:4,:,2:6]

array([[[ 23,  24,  25,  26],
        [ 33,  34, 350,  36]],

       [[ 43,  44,  45,  46],
        [ 53,  54,  55,  56]],

       [[ 63,  64,  65,  66],
        [ 73,  74,  75,  76]]])

In [155]:
narr = np.arange(1,101).reshape((10,10))

In [156]:
narr[3:7,4:8] = np.eye(4)

In [157]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,   1,   0,   0,   0,  39,  40],
       [ 41,  42,  43,  44,   0,   1,   0,   0,  49,  50],
       [ 51,  52,  53,  54,   0,   0,   1,   0,  59,  60],
       [ 61,  62,  63,  64,   0,   0,   0,   1,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [158]:
brr = narr[3:7,4:8].copy()

In [159]:
brr[1:3,1:3] = np.ones(shape=(2,2))

In [160]:
brr

array([[1, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 1]])

In [161]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,   1,   0,   0,   0,  39,  40],
       [ 41,  42,  43,  44,   0,   1,   0,   0,  49,  50],
       [ 51,  52,  53,  54,   0,   0,   1,   0,  59,  60],
       [ 61,  62,  63,  64,   0,   0,   0,   1,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [12]:
n1 = np.array([[1,2,3],[4,5,6]])
n2 = np.array([10,20,30,40,50])

In [13]:
n1+3

array([[4, 5, 6],
       [7, 8, 9]])

In [14]:
n1-3

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [15]:
n1*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [16]:
n1/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [17]:
n1//3

array([[0, 0, 1],
       [1, 1, 2]], dtype=int32)

In [18]:
n1%3

array([[1, 2, 0],
       [1, 2, 0]], dtype=int32)

In [19]:
n1**3

array([[  1,   8,  27],
       [ 64, 125, 216]], dtype=int32)

In [20]:
n1 > 3

array([[False, False, False],
       [ True,  True,  True]])

In [53]:
n1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
n2 = np.array([[10,20,30],[40,50,60]])

In [28]:
n1+n2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [23]:
n1-n2

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [24]:
n1*n2

array([[ 10,  40,  90],
       [160, 250, 360]])

In [25]:
n1 > n2

array([[False, False, False],
       [False, False, False]])

In [26]:
n1*10+n2

array([[ 20,  40,  60],
       [ 80, 100, 120]])

In [29]:
n1 = np.arange(1,21)

In [30]:
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
np.random.shuffle(n1)

In [32]:
n1

array([19,  3,  1,  5, 11, 20,  7, 17, 12,  8, 16, 15,  2,  6, 10,  9,  4,
       13, 18, 14])

In [33]:
n1[[1,4,10]]

array([ 3, 11, 16])

In [34]:
narr = np.arange(1,101).reshape((10,10))

In [38]:
narr[[1,4,8],[0,3,7]]

array([11, 44, 88])

In [39]:
a,b = [1,2]

In [43]:
narr[[True,False,False,True,False,False,False,True,False,True]]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [49]:
n1[n1 > 10]

array([19, 11, 20, 17, 12, 16, 15, 13, 18, 14])

In [52]:
narr[narr > 35]

array([ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [61]:
n2 = np.array([[[1,2],[3,4],[5,6]],[[10,20],[30,40],[50,60]]])

In [58]:
n2

[[[1, 2], [3, 4], [5, 6]], [[10, 20], [30, 40], [50, 60]]]

In [64]:
n2.sum(axis = 2)

array([[  3,   7,  11],
       [ 30,  70, 110]])

In [65]:
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
n1.sum(axis = 0)

array([12, 15, 18])

In [67]:
n1.sum(axis = 1)

array([ 6, 15, 24])

In [69]:
n1.max(axis = 0)

array([7, 8, 9])

In [70]:
n1.min(axis = 1)

array([1, 4, 7])

In [78]:
nb = np.array([True,True,True])

In [79]:
np.all(nb)

True

In [83]:
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
for t in np.nditer(n1):
    print(t)

1
2
3
4
5
6
7
8
9


In [84]:
for t in np.ndenumerate(n1):
    print(t)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((1, 0), 4)
((1, 1), 5)
((1, 2), 6)
((2, 0), 7)
((2, 1), 8)
((2, 2), 9)


In [85]:
n1 = np.array([1,2,3])
n2 = np.array([10,20,30])

In [86]:
np.vstack((n1,n2))

array([[ 1,  2,  3],
       [10, 20, 30]])

In [87]:
np.hstack((n1,n2))

array([ 1,  2,  3, 10, 20, 30])

In [90]:
np.concatenate((n1,n2),axis = 0)

array([ 1,  2,  3, 10, 20, 30])

In [92]:
np.stack((n1,n2),axis=1)

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [93]:
n1

array([1, 2, 3])

In [99]:
l = np.hsplit(n1,3)

In [101]:
l[0][0] = 10

In [102]:
l

[array([10]), array([2]), array([3])]

In [103]:
n1

array([10,  2,  3])

In [104]:
n1 = np.arange(1,13).reshape(4,3)

In [107]:
n1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [109]:
np.array([10,20,30]) + n1

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [110]:
np.array([[10],[20],[30],[40]])

array([[10],
       [20],
       [30],
       [40]])

In [111]:
np.array([[10],[20],[30],[40]]) + n1

array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39],
       [50, 51, 52]])

In [112]:
np.array([10,20,30])+np.array([[10],[20],[30],[40]])

array([[20, 30, 40],
       [30, 40, 50],
       [40, 50, 60],
       [50, 60, 70]])

In [114]:
pop = np.loadtxt('populations.txt')

In [116]:
pop.max(axis = 0)

array([ 1920., 77400., 59400., 48300.])

In [125]:
pop[:,0][pop.argmax(axis = 0)][1:]

array([1903., 1904., 1900.])

In [128]:
n1 = np.arange(1,13).reshape(3,4)

In [129]:
n1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [130]:
n2 = np.array([[1,2,3],[10,20,30]])

In [131]:
n2

array([[ 1,  2,  3],
       [10, 20, 30]])

In [132]:
n2.dot(n1)

array([[ 38,  44,  50,  56],
       [380, 440, 500, 560]])

In [133]:
n2@n1

array([[ 38,  44,  50,  56],
       [380, 440, 500, 560]])