# Numpy
```
pip install numpy
```

- Mathematical Calculations
- Numpy Array Creation
- Shape
- indexing
- data types: b,i,u,f,c,m,M,O,S,u,V (https://numpy.org/doc/1.25/reference/arrays.dtypes.html#arrays-dtypes)
- more creation methods: arange, linspace, ones, zeros, eye, diag
- random numbers: Numpy Random Module
    - rand: Random values in given shape
    - randn: Return samples from the Standard normal distribution
    - randint: Return random integer from low(inclusive) to high(exclusive)
    - random: Return random floats in [0.0,1.0)
    - choice: Generates a random sample from given 1D array
    - Shuffle: Shuffle the contents of the sequence. Discuss np.random.seed()
- reshape: -1 for unknown
- slicing and assignment
- copy and view: share_memory
- operators(Element wise operations)
- and: &, or: |, not: ~ (Bitwise works same as logical in case of boolean Values)
- shape mismatch
- fancy indexing also know as filter
- search: where uses fancy indexing
- Basic reductions: sum, min, max, any, all,argmax, argmin
- Some More Numpy Functions - Statistics: mean, median, average, variance, standard deviation
- iteration: nditer, ndenumerate
- Join: concatenate, stack, hstack, vstack. Note: make a tuple of arays you want to join
- split: array_split, hsplit
- sort: np.sort
- Broadcasting
- Input from Text File
- Questions

In [1]:
!pip install numpy

In [2]:
import numpy as np
print(np.__version__)

1.26.4


In [26]:
l1 = [1,2,3,4]
l2 = [[1,2],[3,4],[5,6]]
l3 = [[[10,20],[30,40]],[[1,2],[3,4]],[[1,2],[3,4]]]

In [48]:
n1 = np.array(l1,dtype='f8')
n2 = np.array(l2,dtype='i1')#1 2 4 8
n3 = np.array(l3)

In [49]:
n2.dtype

dtype('int8')

In [29]:
n2.shape

(3, 2)

In [30]:
n3.shape

(3, 2, 2)

In [32]:
print(l1[2],n1[2])

3 3


In [34]:
# print(l2[1][1], n2[1][1])
print(l2[1][1], n2[1,1])

4 4


In [37]:
print(l3[0][1][0],n3[0,1,0])

30 30


In [38]:
l2[1]

[3, 4]

In [41]:
n2[1]

array([3, 4])

In [42]:
n2[1,2,1]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

more creation methods: arange, linspace, ones, zeros, eye, diag

In [51]:
narr = np.arange(1,11)

In [52]:
narr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [58]:
np.ones(shape = (5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [59]:
np.zeros(shape=(5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [70]:
np.eye(2,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [71]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [73]:
narr = np.arange(1,101)

In [75]:
narr = narr.reshape((10,10))

In [76]:
narr.shape

(10, 10)

In [77]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

random numbers: Numpy Random Module
- rand: Random values in given shape
- randn: Return samples from the Standard normal distribution
- randint: Return random integer from low(inclusive) to high(exclusive)
- random: Return random floats in [0.0,1.0)
- choice: Generates a random sample from given 1D array
- Shuffle: Shuffle the contents of the sequence. Discuss np.random.seed()

In [78]:
np.random.rand(3,2,2)

array([[[0.72016251, 0.2797445 ],
        [0.58225106, 0.33101301]],

       [[0.87272389, 0.96126775],
        [0.30356076, 0.02311402]],

       [[0.6448465 , 0.04280286],
        [0.08959913, 0.68817352]]])

In [79]:
np.random.randn(3,2,2)

array([[[ 1.7905566 , -0.30765327],
        [ 0.2377005 ,  0.5311676 ]],

       [[-1.00601621,  1.17516584],
        [-0.18181411,  0.01083942]],

       [[ 1.25232093,  0.46223587],
        [-0.15167277,  0.50397596]]])

In [80]:
np.random.randint(1,101,size=(5,2))

array([[61, 37],
       [46, 67],
       [82, 97],
       [23, 94],
       [35, 11]])

In [81]:
np.random.random(size=(5,2))

array([[0.34975688, 0.82344578],
       [0.57413113, 0.9799406 ],
       [0.43098886, 0.8674576 ],
       [0.56836466, 0.88558562],
       [0.72232498, 0.80616593]])

In [97]:
np.random.choice(np.array([1,2,3,4,5,6,7,8,9]),size=(5,),replace = True,p = [0,0,0,0,0.3,0.3,0.1,0.3,0])

array([6, 5, 8, 6, 6])

In [101]:
narr = np.arange(1,101).reshape((10,10))
np.random.shuffle(narr)

In [102]:
narr

array([[ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50]])

In [115]:
narr = np.arange(1,101)

In [106]:
narr = narr.reshape((5,2,-1))

In [107]:
narr

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60]],

       [[ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]]])

In [110]:
narr.reshape((-1,))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [113]:
narr[1,1,4] = 350

In [114]:
narr

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34, 350,  36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60]],

       [[ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]]])

In [119]:
narr = narr.reshape((5,2,-1))

In [122]:
narr[1,1,4] = 350

In [137]:
narr[1:4,:,2:6]

array([[[ 23,  24,  25,  26],
        [ 33,  34, 350,  36]],

       [[ 43,  44,  45,  46],
        [ 53,  54,  55,  56]],

       [[ 63,  64,  65,  66],
        [ 73,  74,  75,  76]]])

In [155]:
narr = np.arange(1,101).reshape((10,10))

In [156]:
narr[3:7,4:8] = np.eye(4)

In [157]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,   1,   0,   0,   0,  39,  40],
       [ 41,  42,  43,  44,   0,   1,   0,   0,  49,  50],
       [ 51,  52,  53,  54,   0,   0,   1,   0,  59,  60],
       [ 61,  62,  63,  64,   0,   0,   0,   1,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [158]:
brr = narr[3:7,4:8].copy()

In [159]:
brr[1:3,1:3] = np.ones(shape=(2,2))

In [160]:
brr

array([[1, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 1]])

In [161]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,   1,   0,   0,   0,  39,  40],
       [ 41,  42,  43,  44,   0,   1,   0,   0,  49,  50],
       [ 51,  52,  53,  54,   0,   0,   1,   0,  59,  60],
       [ 61,  62,  63,  64,   0,   0,   0,   1,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [168]:
n1 = np.array([1,2,3,4,5])
n2 = np.array([10,20,30,40,50])

In [177]:
n1 > 3

array([False, False, False,  True,  True])

In [170]:
n1+n2

array([11, 22, 33, 44, 55])